In [6]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

df = pd.read_csv('shoporders_clean.csv',
                 sep=',',
                 encoding='utf-8',
                 decimal='.'
                 )

df

,order_id,quantity,unit_price_chf,discount_pct,customer_loyalty_years,order_month,is_weekend,cat_Elektronik,cat_Haushalt,cat_Kleidung,cat_Sport,land_Deutschland,land_Frankreich,zahlung_Twint,zahlung_Rechnung,total_price_chf
0,1001,1,61.22,15,6.3,8,0,0,0,0,1,1,0,0,0,51.90
1,1002,4,45.42,20,5.2,10,1,0,0,1,0,0,0,1,0,151.51
2,1003,4,20.92,0,0.6,5,0,0,0,0,0,0,0,0,1,82.37
3,1004,3,70.45,0,2.0,7,0,0,0,0,1,0,0,1,0,205.56
4,1005,2,200.08,20,0.4,1,1,1,0,0,0,0,1,0,1,284.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1296,7,17.33,20,0.3,4,0,0,0,0,0,0,0,0,1,94.31
296,1297,8,25.19,10,1.2,2,1,0,0,0,0,1,0,0,0,188.34
297,1298,7,65.89,0,1.3,4,0,0,0,0,1,1,0,0,0,554.65
298,1299,7,80.45,10,1.2,4,0,0,0,0,1,0,1,0,0,566.85
299,1300,2,66.11,0,3.1,2,0,0,1,0,0,1,0,1,0,144.06

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                300 non-null    int64
 1   quantity                300 non-null    int64
 2   unit_price_chf          300 non-null    float64
 3   discount_pct            300 non-null    int64
 4   customer_loyalty_years  300 non-null    float64
 5   order_month             300 non-null    int64
 6   is_weekend              300 non-null    int64
 7   cat_Elektronik          300 non-null    int64
 8   cat_Haushalt            300 non-null    int64
 9   cat_Kleidung            300 non-null    int64
 10  cat_Sport               300 non-null    int64
 11  land_Deutschland        300 non-null    int64
 12  land_Frankreich         300 non-null    int64
 13  zahlung_Twint           300 non-null    int64
 14  zahlung_Rechnung        300 non-null    int64
 15  total_price_chf         300 non-null    float64
dtypes: float64(3), int64(13)
memory usage: 37.6 KB

In [3]:
df.describe()

,order_id,quantity,discount_pct,order_month,is_weekend,cat_Elektronik,cat_Haushalt,cat_Kleidung,cat_Sport,land_Deutschland,land_Frankreich,zahlung_Twint,zahlung_Rechnung
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.00000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,1150.500000,4.420000,7.550000,6.343333,0.310000,0.246667,0.17000,0.270000,0.183333,0.276667,0.136667,0.300000,0.200000
std,86.746758,2.268794,7.633812,3.323996,0.463266,0.431791,0.37626,0.444701,0.387586,0.448098,0.344069,0.459023,0.400668
min,1001.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1075.750000,2.000000,0.000000,3.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1150.500000,4.000000,5.000000,6.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1225.250000,6.000000,15.000000,9.000000,1.000000,0.000000,0.00000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
max,1300.000000,8.000000,20.000000,12.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
X = df[['quantity', 'unit_price_chf', 'customer_loyalty_years']]
y= df['total_price_chf']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state
=42)

print(X_train," || ",X_test," || ",y_train," || ",y_test)

     quantity  unit_price_chf  customer_loyalty_years
232         1           14.84                     2.7
59          6          150.42                     1.2
6           1           79.27                     0.7
185         7           45.72                     2.6
173         3           24.43                     0.3
..        ...             ...                     ...
188         2           73.62                     3.3
71          2           33.68                     1.4
106         3           45.03                     6.2
270         2          188.11                     1.1
102         6           42.07                     0.9

[240 rows x 3 columns]  ||       quantity  unit_price_chf  customer_loyalty_years
203         4          141.27                     1.1
266         6           27.42                     1.3
152         1          238.38                     0.5
9           8           27.93                     1.1
233         6           58.15                     1.2
226         5          147.56                     3.0
196         5           54.72                     0.5
109         8           21.27                     2.6
5           1           23.35                     0.7
175         1          229.63                     2.8
237         1           64.24                     0.8
57          5           57.52                     2.5
218         6           22.34                     0.6
45          5           72.93                     4.0
182         1           49.99                     1.4
221         6           45.22                     1.8
289         1          171.86                     1.6
211         4           67.87                     0.5
148         1           32.79                     1.4
165         6           34.30                     0.4
78          6           61.95                     3.8
113         7           57.37                     0.7
249         6           44.60                     1.0
250         2           58.75                     0.1
104         3           61.65                     0.5
42          7           80.55                     1.0
281         1          128.95                     3.0
295         7           17.33                     0.3
157         5           58.74                     4.0
238         8          189.78                     1.0
17          3          163.79                     1.3
164         7           64.51                     0.6
33          1           37.26                     1.3
24          7           84.14                     9.0
215         3           67.58                     0.2
119         5           58.22                     0.5
7           4           80.53                     1.9
90          2          202.70                     2.3
46          4           56.78                     0.7
73          8           50.29                     1.5
93          6           55.56                     0.3
76          2           45.07                     0.6
286         6          112.47                     0.6
60          6           62.45                     2.0
77          8           68.59                     0.1
63          3           67.08                     0.3
234         8           15.82                     1.0
229         3          213.85                     2.3
111         8          237.39                     1.0
231         2           41.66                     0.3
180         6           29.76                     0.1
144         4           33.52                     5.2
239         4          156.50                     3.2
75          1           40.17                     0.8
297         7           65.89                     1.3
278         3           13.57                     1.9
97          7          142.67                     0.1
92          8           38.56                     2.8
192         3          151.50                     2.7
25          8          149.06                     1.5  ||  232     12.31
59     849.47
6       73.73
185    269.86
173     80.50
        ...
188    119.98
71      69.08
106    121.94
270    401.34
102    227.98
Name: total_price_chf, Length: 240, dtype: float64  ||  203     583.90
266     164.08
152     210.05
9       200.54
233     268.17
226     605.73
196     242.40
109     141.37
5        18.67
175     204.03
237      66.14
57      272.61
218     124.14
45      352.11
182      54.65
221     263.16
289     173.92
211     259.61
148      31.19
165     184.61
78      351.06
113     399.28
249     248.36
250     115.24
104     169.01
42      573.39
281     144.44
295      94.31
157     267.86
238    1312.50
17      478.40
164     350.75
33       38.03
24      494.91
215     209.63
119     230.61
7       307.40
90      341.23
46      184.58
73      319.41
93      303.48
76       74.39
286     582.66
60      341.05
77      517.14
63      202.82
234      99.92
229     657.54
111    1791.66
231      79.94
180     167.92
144     144.59
239     686.78
75       41.53
297     554.65
278      31.92
97      837.62
92      246.60
192     450.81
25     1205.06
Name: total_price_chf, dtype: float64